[build]
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/opportunities"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/opportunities/"
  to = "/"
  status = 301
  force = true

[context.production.environment]
  NODE_ENV = "production" 